# Day 2

In [1]:
#Continue numpy  

In [2]:
import numpy as np

In [3]:
array1=np.arange(20)

In [5]:
print(array1,type(array1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>


In [6]:
array1=array1.reshape(5,4)

In [8]:
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
array1[1][1]=25

In [10]:
print(array1)

[[ 0  1  2  3]
 [ 4 25  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
array1.ndim

2

In [12]:
array1=array1.reshape(5,2,2)

In [13]:
print(array1)

[[[ 0  1]
  [ 2  3]]

 [[ 4 25]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [14]:
print(type(array1),array1.ndim)

<class 'numpy.ndarray'> 3


In [17]:
a_zeros=np.zeros((3,4))

In [18]:
print(a_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
b_zeros=np.zeros((4,4),dtype=np.int16)

In [22]:
print(b_zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
a_ones=np.ones((3,4))

In [24]:
print(a_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
a_ones=a_ones.astype(int)

In [26]:
print(a_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
# Create an empty array

In [28]:
array_empty=np.empty((2,3))

In [29]:
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# Identity martix/array

In [31]:
array_eye=np.eye(3)

In [32]:
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#req - Want to have an even numbers till 20

In [34]:
array_even=np.arange(2,20,2)
print(array_even)

[ 2  4  6  8 10 12 14 16 18]


In [36]:
array_odd=np.arange(1,20,2)
print(array_odd)

[ 1  3  5  7  9 11 13 15 17 19]
